allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") || project.plugins.hasPlugin("com.android.library")) {
            tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach { kotlinTask ->
                def sourceCompatibility = project.android.compileOptions.sourceCompatibility?.toString() ?: "1.8"
                def jvmTarget = kotlinTask.kotlinOptions.jvmTarget ?: ""
                if (sourceCompatibility != jvmTarget) {
                    kotlinTask.kotlinOptions.jvmTarget = sourceCompatibility
                }
            }
            
            // Injects required TFLite asset compression overrides & NDK targets into all Android submodules
            project.android {
                aaptOptions {
                    noCompress 'tflite'
                }
                if (project.plugins.hasPlugin("com.android.application")) {
                    defaultConfig {
                        ndk {
                            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
                        }
                    }
                }
            }
        }
    }
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
